### ISSUE TITLE
Spacebar Key

### ISSUE THREAD

**Issue by beeequeue** [nfriend/ts-key-enum#1]
Should spacebar be added to this enum? Do you have a recommended way to handle it without adding it?

**Comment by beeequeue** [comment]
I'm an idiot nevermind

**Comment by blakekl** [comment]
@BeeeQueue I was just about to recreate this issue. How did you find the spacebar key?

**Comment by beeequeue** [comment]
`" "`

**Comment by blakekl** [comment]
So are you advocating that I should use `if (e.code === ' ') {`  instead of `if (e.code === Key.SpaceBar) {`

I'd think adding a spacebar enum to the list would make sense...

**Comment by beeequeue** [comment]
I personally thought it was fine to use `' '` at the time. Especially since I would've had to wait for `Space` to be added to the enums.

I'll reopen the issue for you since you want it

**Comment by nfriend** [comment]
Thanks @BeeeQueue and @blakekl for the discussion!

At the moment my recommendation is to use `if (ev.key === ' ') { ... }` since the space character is a printable character - see https://github.com/nfriend/ts-key-enum#whats-included.

I can see the appeal of something like `if (ev.key === Key.Space) { ... }`, but this would require a special case since this enum is 100% auto-generated by scraping https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values. That being said, there is an entry for the space character [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Whitespace_keys), so maybe this validates the need for something like `Key.Space` 🤔 

I'll close this issue for now, but I'm willing to be convinced otherwise!
