### ISSUE TITLE
Uglification

### ISSUE THREAD

**Issue by samhh** [nfriend/ts-key-enum#3]
Hey there! Thanks for the awesome library.

I think it could benefit from some uglification. At the moment it ships a non-uglified file that weighs in at 36.3kb. Running this file through [UglifyJS](https://github.com/mishoo/UglifyJS2) alone brings it down to just over 10kb.

**Comment by nfriend** [comment]
Thanks for the suggestion @SamHH!  My assumption is that most consumers of this module are already using a module bundler that supports minification of their final bundle.  Because of this, I don't see adding a minification step to this module's build as a big win.

However, I'm willing to be convinced otherwise if you have a use case 😄.  Also open to PRs.
